export const errorDictionary = {
    'CART_CLEAR_CART_NOT_FOUND': 'No se pudo vaciar el carrito ya que no se encontró.',
    'CART_CLEAR_ERROR': 'Error interno del servidor al vaciar el carrito.',
    'CART_CLEAR_MISSING_ARGUMENTS': 'No se pudo vaciar el carrito ya que no se proporcionó un id.',
    'CART_CREATE_ERROR': 'Error interno del servidor al crear el carrito.',
    'CART_CREATE_MISSING_ARGUMENTS': 'No se pudo crear el carrito porque el id no fue especificado.',
    'CART_DATA_ERROR': 'Error interno del servidor al obtener los datos del carrito.',
    'CART_DELETE_ERROR': 'Error interno del servidor al eliminar el carrito.',
    'CART_NOT_FOUND': 'No se encontró el carrito especificado.',
    'CART_PRODUCT_ADD_ERROR': 'Error interno del servidor al añadir el producto al carrito.',
    'CART_PRODUCT_ADD_MISSING_ARGUMENTS': 'No se pudo añadir el producto al carrito porque el id del producto o el carrito no fueron especificados.',
    'CART_PRODUCT_DELETE_ERROR': 'Error interno del servidor al eliminar producto del carrito.',
    'CART_PRODUCT_DELETE_MISSING_ARGUMENTS': 'No se pudo eliminar el producto del carrito porque no se especificó el id del carrito o del producto.',
    'CART_PRODUCT_DELETE_NOT_FOUND': 'No se pudo buscar el producto en el carrito porque no se especificó el id del carrito o del producto.',
    'CART_PRODUCT_QUANTITY_CHANGE_ERROR': 'Error al aumentar la cantidad del producto en el carrito.',
    'PRODUCT_QUANTITY_CHANGE_INVALID_QUANTITY': 'No se pudo aumentar la cantidad del producto ya que debe ser un numero entero.',
    'CART_PRODUCT_QUANTITY_CHANGE_MISSING_ARGUMENTS': 'No se pudo aumentar la cantidad del producto ya que no se proporcionaron alguno o todos los argumentos.',
    'CART_PRODUCT_SEARCH_ERROR': 'El producto no se encontró en el carrito.',
    'CART_SEARCH_MISSING_ARGUMENTS': 'No se pudo buscar el carrito porque el id no fue especificado.',
    'CARTS_NOT_FOUND': 'No se encontraron carritos.',
    'PRODUCT_CREATE_ERROR': 'Error interno del servidor al crear el producto.',
    'PRODUCT_CREATE_INVALID_QUANTITY': 'El precio y stock deben ser números positivos al crear el producto.',
    'PRODUCT_CREATE_MISSING_ARGUMENTS': 'No se pudo crear el producto ya que no se proporcionaron uno o más datos.',
    'PRODUCT_DELETE_ERROR': 'Error interno del servidor al eliminar el producto.',
    'PRODUCT_DELETE_MISSING_ARGUMENTS': 'No se pudo eliminar el producto ya que no se proporcionó un id.',
    'PRODUCT_DELETE_NOT_FOUND': 'No se encontró el producto a eliminar.',
    'PRODUCT_DELETEBYOWNER_ERROR': 'Error interno del servidor al eliminar productos por owner.',
    'PRODUCT_DELETEBYOWNER_MISSING_ARGUMENTS': 'No se pudo eliminar los productos ya que no se proporcionó un owner.',
    'PRODUCT_GETBYOWNER_ERROR': 'Error interno del servidor al obtener productos por owner.',
    'PRODUCT_GETBYOWNER_MISSING_ARGUMENTS': 'No se pudo obtener los productos ya que no se proporcionó un owner.',
    'PRODUCT_NOT_FOUND': 'No se encontró el producto especificado.',
    'PRODUCT_SEARCH_ERROR': 'Error interno del servidor al buscar el producto',
    'PRODUCT_SEARCH_MISSING_ARGUMENTS': 'No se pudo buscar el producto ya que no se proporcionó un id.',
    'PRODUCT_UPDATE_ERROR': 'Error interno del servidor al actualizar el stock del producto.',
    'PRODUCT_UPDATE_INVALID_QUANTITY': 'La cantidad a añadir debe ser un número positivo al actualizar el producto.',
    'PRODUCT_UPDATE_MISSING_ARGUMENTS': 'No se pudo actualizar el producto ya que no se proporcionó un id.',
    'PRODUCTS_DELETE_ERROR': 'Error interno del servidor al eliminar los productos.',
    'PRODUCTS_DELETE_FROM_ALL_CARTS_ERROR': 'Error interno del servidor al eliminar productos de todos los carritos.',
    'PRODUCTS_DELETE_FROM_ALL_CARTS_MISSING_ARGUMENTS': 'No se pudo eliminar los productos de todos los carritos porque no se proporcionaron los productos.',
    'PRODUCTS_DELETE_MISSING_ARGUMENTS': 'No se pudo eliminar los productos ya que no se proporcionaron.',
    'PRODUCTS_NOT_FOUND': 'No se encontraron productos para el owner especificado.',
    'TICKET_CREATE_ERROR': 'Error interno del servidor al crear el ticket.',
    'TICKET_CREATE_MISSING_ARGUMENTS': 'No se pudo crear el ticket porque faltan argumentos.',
    'TICKET_NOT_FOUND': 'No se encontró el ticket especificado.',
    'TICKET_SEARCH_ERROR': 'Error interno del servidor al buscar el ticket.',
    'TICKET_SEARCH_MISSING_ARGUMENTS': 'No se pudo buscar el ticket porque el código no fue especificado.',
    'USER_CREATE_ERROR': 'Error interno del servidor al crear el usuario.',
    'USER_CREATE_MISSING_ARGUMENTS': 'No se pudo crear el usuario porque faltan argumentos.',
    'USER_DELETE_ERROR': 'Error interno del servidor al eliminar usuarios.',
    'USER_DELETE_MISSING_ARGUMENTS': 'No se proporcionaron correos electrónicos ni fecha para eliminar usuarios.',
    'USER_GET_ERROR': 'Error interno del servidor al obtener los usuarios.',
    'USER_NOT_FOUND': 'No se encontró el usuario especificado.',
    'USER_SEARCH_ERROR': 'Error interno del servidor al buscar el usuario.',
    'USER_SEARCH_MISSING_ARGUMENTS': 'No se pudo buscar el usuario porque el email no fue especificado.',
    'USER_UPDATE_DATE_ERROR': 'Error interno del servidor al actualizar la última conexión del usuario.',
    'USER_UPDATE_DATE_MISSING_ARGUMENTS': 'No se pudo actualizar la última conexión del usuario porque el email no fue especificado.',
    'USER_UPDATE_DOCUMENTS_ERROR': 'Error interno del servidor al actualizar los documentos del usuario.',
    'USER_UPDATE_DOCUMENTS_MISSING_ARGUMENTS': 'No se pudo actualizar los documentos del usuario porque faltan argumentos.',
    'USER_UPDATE_PASSWORD_ERROR': 'Error interno del servidor al actualizar la contraseña del usuario.',
    'USER_UPDATE_PASSWORD_MISSING_ARGUMENTS': 'No se pudo actualizar la contraseña del usuario porque faltan argumentos.',
    'USER_UPDATE_ROLE_ERROR': 'Error interno del servidor al actualizar el rol del usuario.',
    'USER_UPDATE_ROLE_MISSING_ARGUMENTS': 'No se pudo actualizar el rol del usuario porque faltan argumentos.'
};